# Generated by Django 4.1.6 on 2023-02-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weatherModel',
            fields=[
                ('date_time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temp_out', models.FloatField(blank=True)),
                ('low_temp', models.FloatField(blank=True)),
                ('out_hum', models.IntegerField(blank=True)),
                ('dew_pt', models.FloatField(blank=True)),
                ('wind_speed', models.FloatField(blank=True)),
                ('wind_dir', models.CharField(blank=True, max_length=10)),
                ('wind_run', models.FloatField(blank=True)),
                ('hi_speed', models.FloatField(blank=True)),
                ('hi_dir', models.CharField(blank=True, max_length=10)),
                ('wind_chill', models.FloatField(blank=True)),
                ('heat_index', models.FloatField(blank=True)),
                ('thw_index', models.FloatField(blank=True)),
                ('bar', models.FloatField(blank=True)),
                ('rain', models.FloatField(blank=True)),
                ('rain_rate', models.FloatField(blank=True)),
                ('heat_dd', models.FloatField(blank=True)),
                ('cool_dd', models.FloatField(blank=True)),
                ('in_temp', models.FloatField(blank=True)),
                ('in_hum', models.IntegerField(blank=True)),
                ('in_dew', models.FloatField(blank=True)),
                ('in_heat', models.FloatField(blank=True)),
                ('in_emc', models.FloatField(blank=True)),
                ('in_air_density', models.FloatField(blank=True)),
                ('wind_samp', models.IntegerField(blank=True)),
                ('wind_tx', models.IntegerField(blank=True)),
                ('iss_recept', models.FloatField(blank=True)),
                ('arc_int', models.IntegerField(blank=True)),
            ],
        ),
    ]
