# Generated by Django 4.1.6 on 2023-02-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathermodel',
            name='newField',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
