# Generated by Django 4.1.6 on 2023-02-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_weathermodel_newfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathermodel',
            name='anotherField',
            field=models.FloatField(blank=True, default=0.5),
        ),
    ]
